### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by GtaVMasterX** [Boostvolt/tesla_redis#3]
Error: [ioredis] Unhandled error event: [
  {
    "file": "@wtf_redis/tesla_redis.js",
    "line": 4780,
    "name": ""
  },
  {
    "file": "events.js",
    "line": 315,
    "name": "onceWrapper"
  },
  {
    "file": "events.js",
    "line": 116,
    "name": "emitOne"
  },
  {
    "file": "events.js",
    "line": 211,
    "name": "Socket.emit"
  },
  {
    "file": "net.js",
    "line": 561,
    "name": "TCP._handle.close [as _onclose]"
  }
]
Hosted from a local server. Is there a way to fix it?

**Comment by Boostvolt** [comment]
tesla_redis is in early development, currently expects the server to be at 127.0.0.1:6379. The ability to configure tesla_redis, and change this, is in the works.

**Comment by GtaVMasterX** [comment]
I changed it already?
