### ISSUE TITLE
dont can use wtf_banking from this error

### ISSUE THREAD

**Issue by alex98ch** [Boostvolt/tesla_redis#5]
i dont can use anything wtf scripts because the redis gets evertime this error

[91mError: [ioredis] Unhandled error event: [
{
"file": "net.js",
"line": 1128,
"name": "TCPConnectWrap.afterConnect [as oncomplete]"

**Comment by Boostvolt** [comment]
This mod is no longer maintained by wtf_mods and is therefore based on a different framework. Please contact wtf_mods for help.
